spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
logging:
  level:
    root: info
    cn.dyw.notesnook: debug
    org.springframework.security: info
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: trace
    org.springframework.web.servlet.handler: debug
    org.springframework.web.servlet.DispatcherServlet: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    org.springframework.data.mongodb.core.MongoTemplate: debug