spring:
  data:
    mongodb:
      host: 192.168.19.15
      port: 27017
logging:
  level:
    root: info
    cn.dyw.notesnook: debug
    org.springframework.security: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: trace
    org.springframework.web.servlet.handler: debug
    org.springframework.web.servlet.DispatcherServlet: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace