spring:
  application:
    name: notesnook-sync-server-admin
  profiles:
    active: local
  security:
    user:
      name: admin
      password: admin
  jackson:
    serialization:
      write-dates-with-zone-id: true
      write-dates-as-timestamps: true
notesnook:
  app-salt: oVzKtazBo7d8sb7TBvY9jw
springdoc:
  api-docs:
    enabled: true
    path: /doc/v3/api-docs
  swagger-ui:
    path: /doc/swagger-ui.html
    enabled: true